////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$SetReturnPoint", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class SetReturnPointPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte ReturnPointId { get; set; }

        public static string ReturnHelp()
        {
            return "$SetReturnPoint RETURNPOINTID";
        }

        #endregion
    }
}